# Generated by Django 4.2 on 2026-01-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sport_interests',
            field=models.ManyToManyField(blank=True, help_text='Sports this child is interested in', related_name='interested_students', to='leagues.sport'),
        ),
    ]
